# Generated by Django 5.2.7 on 2025-10-20 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('icon', models.CharField(help_text='Emoji ou icône (ex: 📘, 🔬)', max_length=10, verbose_name='icône')),
                ('color', models.CharField(help_text='Couleur hex (ex: #6366F1)', max_length=7, verbose_name='couleur')),
                ('ordre', models.IntegerField(default=0, verbose_name='ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
            options={
                'verbose_name': 'matière',
                'verbose_name_plural': 'matières',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='numéro')),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('ordre', models.IntegerField(default=0, verbose_name='ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='formation.matiere', verbose_name='matière')),
            ],
            options={
                'verbose_name': 'chapitre',
                'verbose_name_plural': 'chapitres',
                'ordering': ['ordre', 'numero'],
                'unique_together': {('matiere', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='question')),
                ('options', models.JSONField(default=list, help_text="Tableau de 4 options ['opt1', 'opt2', 'opt3', 'opt4']", verbose_name='options')),
                ('correct_answer', models.IntegerField(help_text='Index de la bonne réponse (0-3)', verbose_name='réponse correcte')),
                ('explication', models.TextField(blank=True, verbose_name='explication')),
                ('ordre', models.IntegerField(default=0, verbose_name='ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='formation.chapitre', verbose_name='chapitre')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgressionChapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('verrouille', 'Verrouillé'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='verrouille', max_length=20, verbose_name='statut')),
                ('score', models.IntegerField(blank=True, help_text='Score en pourcentage (0-100)', null=True, verbose_name='score')),
                ('temps_ecoule', models.IntegerField(blank=True, help_text='Temps en secondes', null=True, verbose_name='temps écoulé')),
                ('tentatives', models.IntegerField(default=0, verbose_name='nombre de tentatives')),
                ('meilleur_score', models.IntegerField(blank=True, null=True, verbose_name='meilleur score')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='formation.chapitre', verbose_name='chapitre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'progression chapitre',
                'verbose_name_plural': 'progressions chapitres',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'chapitre')},
            },
        ),
    ]
