# Generated by Django 5.2.7 on 2025-10-21 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(help_text="Date d'activation de l'abonnement", verbose_name='date de début')),
                ('date_fin', models.DateField(help_text="Toujours le 31 juillet de l'année scolaire en cours", verbose_name='date de fin')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré'), ('suspendu', 'Suspendu')], default='actif', max_length=20, verbose_name='statut')),
                ('montant_paye', models.IntegerField(help_text="Montant de l'abonnement en FCFA", verbose_name='montant payé')),
                ('reference_paiement', models.CharField(blank=True, max_length=100, verbose_name='référence paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abonnement', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'abonnement',
                'verbose_name_plural': 'abonnements',
                'ordering': ['-created_at'],
            },
        ),
    ]
